services:

  localstack:
    image: localstack/localstack:latest
    container_name: cloud-native-localstack

    ports:
      - "4566:4566"

    environment:
      SERVICES: s3,dynamodb,sqs,iam
      DEBUG: "1"

    volumes:
      - localstack_data:/var/lib/localstack

    networks:
      - cloud-native-network

  api:
    build:
      context: ./backend

    container_name: cloud-native-api

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    networks:
      - cloud-native-network

    depends_on:
      - localstack

  worker:
    build:
      context: ./backend

    container_name: cloud-native-worker

    command:
      - python
      - -m
      - app.worker.worker

    env_file:
      - ./backend/.env

    networks:
      - cloud-native-network

    depends_on:
      - localstack

volumes:
  localstack_data:

networks:
  cloud-native-network:
    driver: bridge