apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: cloud-native
spec:
  replicas: 1

  selector:
    matchLabels:
      app: localstack

  template:
    metadata:
      labels:
        app: localstack

    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4566

          env:
            - name: SERVICES
              value: "s3,dynamodb,sqs,iam"

            - name: DEBUG
              value: "1"

            - name: AWS_DEFAULT_REGION
              value: "us-east-1"

          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: cloud-native
spec:
  selector:
    app: localstack

  ports:
    - port: 4566
      targetPort: 4566

  type: ClusterIP