apiVersion: v1

kind: Secret

metadata:
  name: cloud-native-secret
  namespace: cloud-native

type: Opaque

stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  JWT_SECRET_KEY: s123456789